== Clansuite IRC-LogBot

==== TODO

- re-add cookies for the checkboxes via jquery (really needed?)

=== 0.3.0 - combined 0.1.1/0.2.0

Modifications:
- the filtering feature of v0.2.0 is added
- filtering uses jquery selectors and toggle now
- removed cookie feature
- added links to previous and next days in the navigation
- the link grabber is included only, when viewing the logs of a day
- anchors no longer using href, but name for named anchors

=== 0.2.0 - Original Mircoformats LogBot (mflogbot)

@author  Robert Bachmann
@license GNU/GPLv2

Is a modified version of LogBot-0.1.0 by Robert Bachmann for #microformats ( irc://chat.freenode.net/microformats ).
The source is available via SVN, see http://rbach.priv.at/svn/mflogbot/
Visit http://microformats.org/wiki/mflogbot for more information.
The file "LogBot-20051116.diff" contains the diff-patch against the original LogBot v0.1.0

The main feature of this version is an additional javascript to filter the log of a day.
You can filter JOIN's, QUIT's and PART's, MODE's and the botname itself.
Additionally a cookie can be set to remember these settings.


=== 0.1.1 - Clansuite Fork

Modifications:
- listing of year(s) and month(s) with links in the log overview
- proper display and formatting of day names
- anchors for direct linking to lines of the log for a day (?date=YYYY-MM-DD#LINE)
- link extraction via Clansuite_LinkGrabber and display in a section after the log of a day

=== 0.1.0 - Original version

http://www.jibble.org/logbot/
