== Clansuite IRC-LogBot

This is a combination of a modified IRC Channel Logbot (PircBot) and a PHP based IRC Log Viewer with advanced features. The goal was to make it easier to quote people by linking to the specific item and
easier to find pervious discussions by providing a decent calendar based navigation.

Features:
- LogBot based on PircBot, creates chat log files of your IRC channel
- all messages have an anchored time-signature for easy linking
- calendar based navigation
- jquery based message filtering (bot, user, topic)

Demo: http://irclogs.clansuite.com/

=== Changelog

=== 0.3.0 - Merged 0.2.0 with 0.1.1

Modifications:

- the filtering feature of v0.2.0 is added
- filtering uses jquery selectors and toggle now
- removed cookie feature, google doesn't like them
- added links to previous and next days in the navigation
- the link grabber is included only, when viewing the logs of a day
- anchors no longer using href, but name for named anchors

=== 0.2.0 - Original Mircoformats LogBot (mflogbot)

Author   Robert Bachmann
License  GNU/GPLv2

Is a modified version of LogBot-0.1.0 by Robert Bachmann for #microformats ( irc://chat.freenode.net/microformats ).
The source is available via SVN, see http://rbach.priv.at/svn/mflogbot/
Visit http://microformats.org/wiki/mflogbot for more information.
The file "LogBot-20051116.diff" contains the diff-patch against the original LogBot v0.1.0

The main feature of this version is an additional javascript to filter the log of a day.
You can filter JOIN's, QUIT's and PART's, MODE's and the botname itself.
Additionally a cookie can be set to remember these settings.

=== 0.1.1 - Clansuite Fork

Modifications:

- listing of year(s) and month(s) with links in the log overview
- proper display and formatting of day names
- anchors for direct linking to lines of the log for a day (?date=YYYY-MM-DD#LINE)
- link extraction via Clansuite_LinkGrabber and display in a section after the log of a day

=== 0.1.0 - Original version

http://www.jibble.org/logbot/

=== Related projects

Mainly for inspiration:

- https://github.com/KevBurnsJr/irc-log-viewer & http://lab.kevburnsjr.com/irc-log-viewer/
- https://github.com/firebreath/irc-logviewer & http://logs.firebreath.org/
- http://logs.simon.geek.nz/index.php
  Meow. Copycats. Navigation is the same as ours, except the missing calendar navigation.